### ISSUE TITLE
Repo status?

### ISSUE THREAD

**Issue by joshmoore** [spacetx/spacetx-writer#5]
Is there interest in trying to get this building again? Or would archiving the repo be more appropriate?

**Comment by berl** [comment]
well @joshmoore  it looks like @stephanpreibisch is still interested ... see #6 !

**Comment by StephanPreibisch** [comment]
yes, but I am doing it for benchmark-purposes though (comparing StarFish) ... I got it fixed for my specific case by changing the source. But maybe others would be interested as well ...

**Comment by joshmoore** [comment]
:wink: :wave: -- just to bring others to the party, @tischi recently inquired about starfish itself (not just this repo) at which point I asked @neuromusic about that status (and he was going to talk to @berl) -- basically along the lines of is there interest in introducing OME-Zarr into the stack. I'll leave others to comment and take a look at #6 to see if there's something that I can fix. (Diffs welcome, @StephanPreibisch).

**Comment by tischi** [comment]
I'll likely have a zoom meeting with @neuromusic next week, to discuss, among other things, using an OME-ZARR based output format.

**Comment by joshmoore** [comment]
Closing this since people have woken up again.
