### ISSUE TITLE
t<1-5>.tif patterns do not work

### ISSUE THREAD

**Issue by StephanPreibisch** [spacetx/spacetx-writer#6]
Hi, today I tried to resave a large 3d image with 1550 z planes. I tried encoding it as "z_<0000-1549>.tif" in the filename, but that does not work. I looked at the source code and it seems that this feature is not implemented because it immediately checks that the filename exists, which of course it doesn't - it would need to be parsed first and  "z_<0000-1549>.tif" would have to be expanded into 1550 filenames:
https://github.com/spacetx/spacetx-writer/blob/d74cb32812999be36cab13104358839f8790126c/src/main/java/spacetx/FOVTool.java#L179-L181

I added my 1500 filenames by hand using a for-loop instead, which works fine. So my guess would be that somehow, parsing of the filename would have to happen just before the code snippet I posted above. Or am I doing something wrong or missing something?

Thanks so much,
Stephan

**Comment by joshmoore** [comment]
If I understand correct, @StephanPreibisch, then my suggestion & intent (from https://github.com/spacetx/spacetx-writer#grouping-files) would be to do:

```
$ echo 'z_<0000-1549>.tif' > my.pattern
$ spacetx-writer ... my.pattern
```

**Comment by StephanPreibisch** [comment]
Ah, so maybe this is just a misunderstanding then. I assumed the code would do the parsing ...

**Comment by joshmoore** [comment]
I can't remember why I didn't _also_ enable that, but I assume that I ran into some issue leading to the type of changes you needed locally.
